### ISSUE TITLE
Namespace issue

### ISSUE THREAD

**Issue by opheliadesign** [Infinety/laravel-sweet-alert#1]
Namespace on `AlertServiceProvider.php` is set to `Infinety/SweetAlert`, should be ` Infinety\SweetAlert` - note the direction of the slash.

**Comment by billythekid** [comment]
There's a [pull request](https://github.com/Infinety/laravel-sweet-alert/pull/2) fixing this. hopefully it'll be merged soon.

**Comment by lstables** [comment]
@opheliadesign @billythekid Fixed and merged pull request.
