### ISSUE TITLE
[Request] Pass parameter to the alert

### ISSUE THREAD

**Issue by jpmurray** [Infinety/laravel-sweet-alert#11]
Could we be able to pass parameter to the alert? For example

```
alert($title, $message, $timer, $showConfirmButton);
```

**Comment by lstables** [comment]
I can't see why not, if you want to create a pull request, I'll get this included. @jpmurray

**Comment by jpmurray** [comment]
I'll look into this then! ;-)

**Comment by lstables** [comment]
Cool, just submit pull request and I'll merge it.
